### ISSUE TITLE
Mobile view: Embeds & Some text goes beyond post

### ISSUE THREAD

**Issue by itstooobi** [ShortTechCoding/ingenious#4]
![image](https://user-images.githubusercontent.com/17430176/78502500-bb87e580-7761-11ea-941d-cd56f0055007.png)

**Comment by tobimori** [comment]
~~Fixed by 9bed812~~

**Comment by thilobillerbeck** [comment]
fixed by 002dc148e11e4a0be165f6f48555e62d14c8ddf2

**Comment by tobimori** [comment]
Still not fixed.

**Comment by tobimori** [comment]
![](https://cdn.discordapp.com/attachments/696299792439181312/697032472835260506/Screenshot_20200407-012213_Firefox_Beta.jpg)
