### ISSUE TITLE
Embeds not centered

### ISSUE THREAD

**Issue by itstooobi** [ShortTechCoding/ingenious#5]
![image](https://user-images.githubusercontent.com/17430176/78502642-65677200-7762-11ea-9389-07e6d2fcb4a4.png)

![image](https://user-images.githubusercontent.com/17430176/78502672-862fc780-7762-11ea-9cce-7c2082d13377.png)

**Comment by tobimori** [comment]
Closed by 9bed812

**Comment by tobimori** [comment]
Still not fixed

**Comment by tobimori** [comment]
![](https://cdn.discordapp.com/attachments/696299792439181312/696790616386044029/unknown.png)
